files: river
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        types: [python]
        entry: black

      - id: flake8
        name: flake8
        language: python
        types: [python]
        entry: flake8

      - id: isort
        name: isort
        language: python
        types: [python]
        entry: isort
        args: ["--profile", "black"]
